data,temp_1,int,0
data,temp_2,int,1
data,temp_3,int,1000
data,g,int,0
data,g_zero,int,0
data,g_one,int,0
data,g_two,int,0
data,g_three,int,0
main
call,myfunc
exit
fun_label,myfunc
=,g_zero,g
ifgoto,beq,g_zero,g,D.2047
goto,D.2046
label,D.2046
ret
label,D.2047
=,g_one,g
print_intv,g_one
=,g_two,g
-,g_three,g_two,temp_2
=,g,g_three
call,myfunc